"""Generate the ``conf.d/provider_proxies.conf`` Nginx include for the
phone-provider TLS-interception proxy.

For each hostname in :data:`PROVIDER_HOSTNAMES` the script emits a
dedicated HTTPS server block that:

1.  Terminates TLS using the leaf cert previously produced by
    :mod:`app.sandbox.scripts.generate_provider_certs`.
2.  Matches exactly on ``server_name`` so SNI routes to the right cert.
3.  Rewrites the request URI by **prepending** the provider-specific
    ``/sandbox/{provider}`` prefix then ``proxy_pass``-es to the
    FastAPI upstream.  The original ``Host`` header is preserved so the
    emulator can distinguish between e.g. ``api.twilio.com`` and
    ``messaging.twilio.com`` (which take different request paths).

The script is executed from the s6 ``init-provider-proxies`` oneshot
BEFORE Nginx starts, so Nginx finds the include on first ``-s reload``.

Idempotent — overwrites the target file with up-to-date content every
boot.  The only environment knobs are the output path and whether to
actually enable the proxies (so prod deployments can skip emission).
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

from app.sandbox.scripts.generate_provider_certs import PROVIDER_HOSTNAMES

logger = logging.getLogger("mailcue.sandbox.nginx")


# Hostname → ``/sandbox/{provider}`` path prefix.  Centralised here so
# the cert generator, Nginx generator, and Mailcue routing share the
# same source of truth.
HOSTNAME_TO_PREFIX: dict[str, str] = {
    # Twilio family
    "api.twilio.com": "/sandbox/twilio",
    "trusthub.twilio.com": "/sandbox/twilio",
    "messaging.twilio.com": "/sandbox/twilio",
    "numbers.twilio.com": "/sandbox/twilio",
    # Bandwidth family
    "messaging.bandwidth.com": "/sandbox/bandwidth",
    "voice.bandwidth.com": "/sandbox/bandwidth",
    "dashboard.bandwidth.com": "/sandbox/bandwidth",
    "numbers.bandwidth.com": "/sandbox/bandwidth",
    # Vonage / Nexmo
    "api.nexmo.com": "/sandbox/vonage",
    "rest.nexmo.com": "/sandbox/vonage",
    "api.vonage.com": "/sandbox/vonage",
    # Plivo
    "api.plivo.com": "/sandbox/plivo",
    # Telnyx
    "api.telnyx.com": "/sandbox/telnyx",
}


_NGINX_BLOCK = """\
# -----------------------------------------------------------------------------
#  {hostname} → {prefix}
#  Generated by app.sandbox.scripts.generate_provider_nginx — do not edit.
# -----------------------------------------------------------------------------
server {{
    listen                    443 ssl http2;
    server_name               {hostname};

    ssl_certificate           {leaves_dir}/{hostname}/fullchain.pem;
    ssl_certificate_key       {leaves_dir}/{hostname}/privkey.pem;
    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_ciphers               ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_session_cache         shared:SSL_PROVIDERS:10m;
    ssl_session_timeout       1d;

    client_max_body_size      25m;

    # Expose the Mailcue CA + fingerprint so fase image builds can pin it.
    location = /__mailcue_provider_ca.crt {{
        alias {public_ca_path};
        default_type application/x-x509-ca-cert;
        add_header Cache-Control "public, max-age=60";
    }}
    location = /__mailcue_provider_ca_fingerprint.txt {{
        alias {public_fp_path};
        default_type text/plain;
        add_header Cache-Control "public, max-age=60";
    }}

    # Every other request is rewritten and forwarded to the FastAPI
    # upstream.  The ``$request_uri`` carries the full original path +
    # query string; we prepend the provider's sandbox prefix.  The
    # emulator sees exactly what the real provider would have seen
    # after the sandbox strip.
    location / {{
        proxy_pass          http://api_backend{prefix}$request_uri;
        proxy_http_version  1.1;
        proxy_set_header    Host              $host;
        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
        proxy_set_header    X-Forwarded-Host  $host;
        proxy_set_header    X-Mailcue-Provider-Host $host;
        proxy_set_header    Connection        "";

        proxy_connect_timeout 10s;
        proxy_read_timeout    60s;
        proxy_send_timeout    60s;
    }}
}}
"""


_HEADER = """\
# =============================================================================
#  Phone-provider TLS-interception proxies — autogenerated
#  Source: app/sandbox/scripts/generate_provider_nginx.py
#
#  Enabled only when MAILCUE_PROVIDER_PROXIES_ENABLED=true (default: true in
#  dev).  To disable in production, set the env var to ``false``; the file
#  is then replaced with this header only (no server blocks).
# =============================================================================

"""


def _default_leaves_dir() -> str:
    return os.environ.get(
        "MAILCUE_PROVIDER_LEAVES_DIR",
        "/var/lib/mailcue/certs/provider_leaves",
    )


def _default_ca_paths() -> tuple[str, str]:
    base = os.environ.get(
        "MAILCUE_PROVIDER_LEAVES_DIR",
        "/var/lib/mailcue/certs/provider_leaves",
    )
    parent = str(Path(base).parent)
    return (
        f"{parent}/provider_ca.crt",
        f"{parent}/provider_ca_fingerprint.txt",
    )


def _default_output_path() -> Path:
    return Path(
        os.environ.get(
            "MAILCUE_PROVIDER_PROXIES_CONF",
            "/etc/nginx/conf.d/provider_proxies.conf",
        )
    )


def _enabled() -> bool:
    raw = os.environ.get("MAILCUE_PROVIDER_PROXIES_ENABLED", "true").strip().lower()
    return raw in ("1", "true", "yes", "on")


def render() -> str:
    if not _enabled():
        logger.info("Provider proxies disabled via MAILCUE_PROVIDER_PROXIES_ENABLED")
        return _HEADER + "#  Disabled.\n"

    leaves_dir = _default_leaves_dir()
    public_ca, public_fp = _default_ca_paths()

    blocks: list[str] = []
    for hostname in PROVIDER_HOSTNAMES:
        prefix = HOSTNAME_TO_PREFIX[hostname]
        blocks.append(
            _NGINX_BLOCK.format(
                hostname=hostname,
                prefix=prefix,
                leaves_dir=leaves_dir,
                public_ca_path=public_ca,
                public_fp_path=public_fp,
            )
        )
    return _HEADER + "\n".join(blocks)


def run() -> int:
    logging.basicConfig(level=logging.INFO, format="[%(name)s] %(message)s")
    out = _default_output_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    content = render()
    out.write_text(content, encoding="utf-8")
    os.chmod(out, 0o644)
    logger.info(
        "Wrote Nginx provider-proxy config to %s (%d bytes, %d servers)",
        out,
        len(content),
        0 if not _enabled() else len(PROVIDER_HOSTNAMES),
    )
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    sys.exit(run())


if __name__ == "__main__":
    main()
