#!/bin/sh
# =============================================================================
# MailCue — Container Initialisation (oneshot)
# Runs once before any long-running services start.
# =============================================================================
set -eu

MAILCUE_MODE="${MAILCUE_MODE:-test}"
echo "MailCue mode: ${MAILCUE_MODE}"

DOMAIN="${MAILCUE_DOMAIN:-mailcue.local}"
HOSTNAME="${MAILCUE_HOSTNAME:-mail.${DOMAIN}}"
ADMIN_USER="${MAILCUE_ADMIN_USER:-admin}"
ADMIN_PASSWORD="${MAILCUE_ADMIN_PASSWORD:-mailcue}"
SECRET_KEY="${MAILCUE_SECRET_KEY:-}"
DB_PATH="${MAILCUE_DB_PATH:-/var/lib/mailcue/mailcue.db}"
DB_ENCRYPTION_KEY="${MAILCUE_DATABASE_ENCRYPTION_KEY:-}"
SSL_DIR="/etc/ssl/mailcue"
DKIM_DIR="/etc/opendkim/keys/${DOMAIN}"
VMAIL_BASE="/var/mail/vhosts"
DOVECOT_USERS="/etc/dovecot/users"

# Set the container's system hostname so SMTP EHLO uses the correct value
# instead of the Docker container ID (e.g., "1c7faeb9da74").
hostname "${HOSTNAME}" 2>/dev/null || true

echo "[init-mailcue] Starting initialisation for domain=${DOMAIN}"

# -------------------------------------------------------------------------
# 1. Generate self-signed TLS certificates (if not already present)
# -------------------------------------------------------------------------
if [ ! -f "${SSL_DIR}/server.crt" ] || [ ! -f "${SSL_DIR}/server.key" ]; then
    echo "[init-mailcue] Generating TLS certificates (CA + server)..."
    mkdir -p "${SSL_DIR}"

    SERIAL_HEX=$(openssl rand -hex 8)

    # --- Root CA ---
    cat > /tmp/mailcue-ca.cnf << 'CACNF'
[req]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_ca

[dn]
C            = US
ST           = Georgia
L            = Stone Mountain
O            = Olib AI
OU           = MailCue Certificate Authority
CN           = MailCue Root CA
emailAddress = security@olib.ai

[v3_ca]
basicConstraints     = critical, CA:TRUE, pathlen:0
keyUsage             = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always, issuer
nsComment            = "MailCue Root CA - Generated by MailCue (olib.ai)"
CACNF

    openssl req -x509 -newkey rsa:4096 -nodes \
        -keyout "${SSL_DIR}/ca.key" \
        -out "${SSL_DIR}/ca.crt" \
        -days 3650 \
        -config /tmp/mailcue-ca.cnf 2>/dev/null

    # --- Server certificate CSR config ---
    cat > /tmp/mailcue-server-req.cnf << REQCNF
[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn

[dn]
C            = US
ST           = Georgia
L            = Stone Mountain
O            = Olib AI
OU           = MailCue Mail Server
CN           = ${HOSTNAME}
emailAddress = security@olib.ai
REQCNF

    # --- Server certificate extensions (applied at signing time) ---
    cat > /tmp/mailcue-server-ext.cnf << EXTCNF
basicConstraints       = critical, CA:FALSE
keyUsage               = critical, digitalSignature, keyEncipherment, keyAgreement
extendedKeyUsage       = serverAuth, clientAuth, emailProtection
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid, issuer
subjectAltName         = @alt_names
nsComment              = "MailCue Server Certificate - Generated by MailCue (olib.ai)"
certificatePolicies    = 2.23.140.1.2.1

[alt_names]
DNS.1  = ${HOSTNAME}
DNS.2  = smtp.${DOMAIN}
DNS.3  = imap.${DOMAIN}
DNS.4  = pop3.${DOMAIN}
DNS.5  = webmail.${DOMAIN}
DNS.6  = ${DOMAIN}
DNS.7  = *.${DOMAIN}
DNS.8  = localhost
IP.1   = 127.0.0.1
IP.2   = ::1
email.1 = security@olib.ai
EXTCNF

    # Generate server key and CSR
    openssl req -newkey rsa:2048 -nodes \
        -keyout "${SSL_DIR}/server.key" \
        -out /tmp/mailcue-server.csr \
        -config /tmp/mailcue-server-req.cnf 2>/dev/null

    # Sign server cert with CA, applying extensions
    openssl x509 -req \
        -in /tmp/mailcue-server.csr \
        -CA "${SSL_DIR}/ca.crt" \
        -CAkey "${SSL_DIR}/ca.key" \
        -set_serial "0x${SERIAL_HEX}" \
        -days 3650 \
        -sha256 \
        -extfile /tmp/mailcue-server-ext.cnf \
        -out "${SSL_DIR}/server-only.crt" 2>/dev/null

    # Build full chain: server cert + CA cert
    cat "${SSL_DIR}/server-only.crt" "${SSL_DIR}/ca.crt" > "${SSL_DIR}/server.crt"

    chmod 600 "${SSL_DIR}/server.key" "${SSL_DIR}/ca.key"
    chmod 644 "${SSL_DIR}/server.crt" "${SSL_DIR}/ca.crt" "${SSL_DIR}/server-only.crt"
    rm -f /tmp/mailcue-ca.cnf /tmp/mailcue-server-req.cnf /tmp/mailcue-server-ext.cnf /tmp/mailcue-server.csr
    echo "[init-mailcue] TLS certificates generated (CA + server chain)."
else
    echo "[init-mailcue] TLS certificate already exists, skipping generation."
fi

# -------------------------------------------------------------------------
# 2. Generate DKIM keys (if not already present)
# -------------------------------------------------------------------------
if [ ! -f "${DKIM_DIR}/mail.private" ]; then
    echo "[init-mailcue] Generating DKIM keys for ${DOMAIN}..."
    mkdir -p "${DKIM_DIR}"

    opendkim-genkey -b 2048 -h sha256 \
        -d "${DOMAIN}" -s mail \
        -D "${DKIM_DIR}/"

    chown -R opendkim:opendkim /etc/opendkim/keys/
    chmod 600 "${DKIM_DIR}/mail.private"
    echo "[init-mailcue] DKIM keys generated."
else
    echo "[init-mailcue] DKIM keys already exist, skipping generation."
fi

# -------------------------------------------------------------------------
# 3. Template mail server configuration files with runtime values
# -------------------------------------------------------------------------
echo "[init-mailcue] Templating configuration files..."

# --- Postfix main.cf ---
sed -i \
    -e "s/\${MAILCUE_DOMAIN}/${DOMAIN}/g" \
    -e "s/\${MAILCUE_HOSTNAME}/${HOSTNAME}/g" \
    /etc/postfix/main.cf

# --- Dovecot postmaster address ---
sed -i \
    -e "s/postmaster@mailcue\.local/postmaster@${DOMAIN}/g" \
    /etc/dovecot/dovecot.conf

# --- Postfix catch-all domain table ---
# Regexp table: match any domain.  Does NOT need postmap.
printf '/^.+$/    OK\n' > /etc/postfix/virtual_domains_catchall

# Keep legacy hash files for backward compat but they are no longer
# referenced by the main delivery path (catch-all replaces them).
touch /etc/postfix/virtual_mailboxes
touch /etc/postfix/virtual_aliases
touch /etc/postfix/virtual_domains

# --- OpenDKIM tables ---
echo "mail._domainkey.${DOMAIN}    ${DOMAIN}:mail:${DKIM_DIR}/mail.private" \
    > /etc/opendkim/KeyTable
echo "*@${DOMAIN}    mail._domainkey.${DOMAIN}" \
    > /etc/opendkim/SigningTable
cat > /etc/opendkim/TrustedHosts << TRUSTED
127.0.0.1
::1
localhost
${HOSTNAME}
*.${DOMAIN}
TRUSTED

chown -R opendkim:opendkim /etc/opendkim/

# -------------------------------------------------------------------------
# 3b. Configure OpenDMARC
# -------------------------------------------------------------------------
echo "[init-mailcue] Configuring OpenDMARC..."
mkdir -p /var/run/opendmarc
chown opendmarc:opendmarc /var/run/opendmarc 2>/dev/null || true

# Template the config with the domain
sed -i \
    -e "s/postmaster@localhost/postmaster@${DOMAIN}/g" \
    /etc/opendmarc/opendmarc.conf 2>/dev/null || true

# -------------------------------------------------------------------------
# 3b2. Compile Sieve scripts & prepare SpamAssassin directories
# -------------------------------------------------------------------------
echo "[init-mailcue] Compiling Sieve scripts..."
if [ -f /etc/dovecot/sieve/before.d/spam-to-junk.sieve ]; then
    sievec /etc/dovecot/sieve/before.d/spam-to-junk.sieve || true
fi

# Ensure SpamAssassin Bayes database directory exists
mkdir -p /var/lib/spamassassin
chown debian-spamd:debian-spamd /var/lib/spamassassin 2>/dev/null || true


# -------------------------------------------------------------------------
# 3c. Configure smarthost relay (if MAILCUE_RELAY_HOST is set)
# -------------------------------------------------------------------------
RELAY_HOST="${MAILCUE_RELAY_HOST:-}"
RELAY_PORT="${MAILCUE_RELAY_PORT:-587}"
RELAY_USER="${MAILCUE_RELAY_USER:-}"
RELAY_PASSWORD="${MAILCUE_RELAY_PASSWORD:-}"

if [ -n "${RELAY_HOST}" ]; then
    if [ -n "${RELAY_USER}" ] && [ -n "${RELAY_PASSWORD}" ]; then
        # Authenticated smarthost (SendGrid / Mailgun / AWS SES / Postmark / ...).
        # Enforce TLS — SASL credentials must never traverse plaintext.
        echo "[init-mailcue] Configuring authenticated smarthost relay: ${RELAY_HOST}:${RELAY_PORT}"
        cat >> /etc/postfix/main.cf << RELAY
# --- Smarthost relay (auto-configured, SASL + TLS) ---
relayhost = [${RELAY_HOST}]:${RELAY_PORT}
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_tls_security_level = encrypt
RELAY
        echo "[${RELAY_HOST}]:${RELAY_PORT} ${RELAY_USER}:${RELAY_PASSWORD}" > /etc/postfix/sasl_passwd
        postmap /etc/postfix/sasl_passwd
        chmod 600 /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db
        echo "[init-mailcue] Authenticated smarthost relay configured."
    else
        # Trusted relay on a private network — typically the MailCue
        # tunnel sidecar (mailcue-relay-sidecar) listening on a Docker
        # bridge / unix-domain hop. No SASL, no STARTTLS required:
        # confidentiality is provided by the Noise IK tunnel between
        # the sidecar and the remote edge, not by the loopback hop.
        echo "[init-mailcue] Configuring trusted relay (no SASL, no TLS): ${RELAY_HOST}:${RELAY_PORT}"
        cat >> /etc/postfix/main.cf << RELAY
# --- Trusted relay (auto-configured, plain TCP) ---
relayhost = [${RELAY_HOST}]:${RELAY_PORT}
smtp_sasl_auth_enable = no
smtp_tls_security_level = none
RELAY
        echo "[init-mailcue] Trusted relay configured."
    fi
fi

# -------------------------------------------------------------------------
# 3d. Production mode hardening (if MAILCUE_MODE=production)
# -------------------------------------------------------------------------
if [ "$MAILCUE_MODE" = "production" ]; then
    echo "[init-mailcue] Applying production mode hardening..."

    # --- Postfix production hardening ---
    echo "[init-mailcue] [production] Hardening Postfix..."
    postconf -e "smtpd_reject_unlisted_recipient=yes"
    postconf -e "mynetworks=127.0.0.0/8"
    postconf -e "virtual_mailbox_maps=hash:/etc/postfix/virtual_mailboxes"

    # Create empty virtual_mailboxes and postmap it
    touch /etc/postfix/virtual_mailboxes
    postmap /etc/postfix/virtual_mailboxes

    # Add SPF policy check to smtpd_recipient_restrictions
    postconf -e "smtpd_recipient_restrictions=permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, check_policy_service unix:private/policyd-spf"

    # Switch virtual_mailbox_domains from regexp catchall to hash table
    postconf -e "virtual_mailbox_domains=hash:/etc/postfix/virtual_domains"

    # Create virtual_domains with just the configured domain and postmap it
    echo "${DOMAIN}    OK" > /etc/postfix/virtual_domains
    postmap /etc/postfix/virtual_domains

    # --- Port 465 (SMTPS) — implicit TLS on port 465 ---
    echo "[init-mailcue] [production] Adding SMTPS (port 465) to master.cf..."
    cat >> /etc/postfix/master.cf << 'SMTPS'

# ---- Port 465 — SMTPS (implicit TLS, production mode) --------------------
smtps     inet  n       -       n       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_tls_auth_only=yes
  -o smtpd_reject_unlisted_recipient=yes
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
  -o smtpd_milters=unix:/var/run/opendkim/opendkim.sock
  -o non_smtpd_milters=unix:/var/run/opendkim/opendkim.sock
SMTPS

    # --- Dovecot production hardening ---
    echo "[init-mailcue] [production] Hardening Dovecot..."

    # Remove/comment out the catch-all static passdb (nopassword=y)
    sed -i '/^# Catch-all passdb:/,/^}/ s/^/#/' /etc/dovecot/dovecot.conf

    # Remove/comment out the catch-all fallback userdb (allow_all_users=yes)
    sed -i '/^# Catch-all fallback userdb:/,/^}/ s/^/#/' /etc/dovecot/dovecot.conf

    # Set ssl = required instead of ssl = yes
    sed -i 's/^ssl = yes$/ssl = required/' /etc/dovecot/dovecot.conf

    # Set disable_plaintext_auth = yes
    sed -i '/^ssl = required$/a disable_plaintext_auth = yes' /etc/dovecot/dovecot.conf

    # Enable quota plugin in imap and lmtp protocol sections
    sed -i '/^protocol imap {/a\  mail_plugins = $mail_plugins quota' /etc/dovecot/dovecot.conf
    sed -i '/^protocol lmtp {/a\  mail_plugins = $mail_plugins quota' /etc/dovecot/dovecot.conf

    # --- OpenDMARC production hardening ---
    echo "[init-mailcue] [production] Hardening OpenDMARC..."
    sed -i 's/^RejectFailures          false$/RejectFailures          true/' /etc/opendmarc/opendmarc.conf

    # --- TLS certificate setup ---
    echo "[init-mailcue] [production] Configuring TLS certificates..."
    mkdir -p /etc/ssl/mailcue
    mkdir -p /var/www/acme-challenge

    MAILCUE_TLS_CERT_PATH="${MAILCUE_TLS_CERT_PATH:-}"
    MAILCUE_TLS_KEY_PATH="${MAILCUE_TLS_KEY_PATH:-}"
    MAILCUE_ACME_EMAIL="${MAILCUE_ACME_EMAIL:-}"

    # If custom TLS cert/key paths are provided, symlink them into place
    if [ -n "${MAILCUE_TLS_CERT_PATH}" ] && [ -n "${MAILCUE_TLS_KEY_PATH}" ]; then
        echo "[init-mailcue] [production] Using custom TLS cert: ${MAILCUE_TLS_CERT_PATH}"
        ln -sf "${MAILCUE_TLS_CERT_PATH}" /etc/ssl/mailcue/fullchain.pem
        ln -sf "${MAILCUE_TLS_KEY_PATH}" /etc/ssl/mailcue/privkey.pem
    # If Let's Encrypt certs already exist from a previous run (persisted volume)
    elif [ -f "/etc/letsencrypt/live/${HOSTNAME}/fullchain.pem" ]; then
        echo "[init-mailcue] [production] Found existing Let's Encrypt cert for ${HOSTNAME}"
        ln -sf "/etc/letsencrypt/live/${HOSTNAME}/fullchain.pem" /etc/ssl/mailcue/fullchain.pem
        ln -sf "/etc/letsencrypt/live/${HOSTNAME}/privkey.pem" /etc/ssl/mailcue/privkey.pem
    fi

    # Note: If MAILCUE_ACME_EMAIL is set but no cert exists yet, certbot will
    # run AFTER Nginx starts via the post-start script (acme-setup), because
    # certbot needs port 80 to be serving the ACME challenge.

    # --- Nginx HTTPS setup (only if certs already available) ---
    if [ -f /etc/ssl/mailcue/fullchain.pem ] && [ -f /etc/ssl/mailcue/privkey.pem ]; then
        echo "[init-mailcue] [production] Configuring Nginx HTTPS..."
        mkdir -p /etc/nginx/conf.d

        cat > /etc/nginx/conf.d/https.conf << 'NGINXHTTPS'
# =============================================================================
# Nginx HTTPS — MailCue Production Mode (auto-generated by init-mailcue)
# =============================================================================

# Redirect HTTP to HTTPS (except ACME challenge)
server {
    listen 80;
    server_name _;

    # Allow ACME challenge over HTTP for cert renewal
    location /.well-known/acme-challenge/ {
        root /var/www/acme-challenge;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server block
server {
    listen 443 ssl http2;
    server_name _;

    ssl_certificate     /etc/ssl/mailcue/fullchain.pem;
    ssl_certificate_key /etc/ssl/mailcue/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    # HSTS
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    root /var/www/mailcue;
    index index.html;

    # --- API proxy ---
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection        "";
        proxy_connect_timeout 10s;
        proxy_read_timeout    60s;
        proxy_send_timeout    60s;
    }

    # --- Sandbox proxy ---
    location /sandbox/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection        "";
        proxy_connect_timeout 10s;
        proxy_read_timeout    60s;
        proxy_send_timeout    60s;
    }

    # --- HTTP Bin proxy ---
    location /httpbin/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection        "";
        proxy_connect_timeout 10s;
        proxy_read_timeout    60s;
        proxy_send_timeout    60s;
    }

    # --- SSE stream ---
    location /api/v1/events/stream {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection        "";
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding off;
        proxy_read_timeout 3600s;
        add_header X-Accel-Buffering no;
    }

    # --- Well-known paths ---
    location /.well-known/acme-challenge/ {
        root /var/www/acme-challenge;
        try_files $uri =404;
    }

    location /.well-known/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- Static frontend ---
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
NGINXHTTPS
        echo "[init-mailcue] [production] Nginx HTTPS configured."
    else
        if [ -n "${MAILCUE_ACME_EMAIL}" ]; then
            echo "[init-mailcue] [production] ACME email set — certbot will run after Nginx starts."
        else
            echo "[init-mailcue] [production] No TLS cert found. Set MAILCUE_ACME_EMAIL for automatic Let's Encrypt, or provide MAILCUE_TLS_CERT_PATH/MAILCUE_TLS_KEY_PATH."
        fi
    fi

    echo "[init-mailcue] Production mode hardening complete."
fi

# -------------------------------------------------------------------------
# 4. Generate a secret key if none provided
# -------------------------------------------------------------------------
if [ -z "${SECRET_KEY}" ] && [ -f /var/lib/mailcue/.secret_key ]; then
    # Reuse the previously persisted key so encrypted TOTP secrets remain valid.
    SECRET_KEY=$(cat /var/lib/mailcue/.secret_key)
    echo "[init-mailcue] Loaded MAILCUE_SECRET_KEY from persisted file."
elif [ -z "${SECRET_KEY}" ]; then
    SECRET_KEY=$(openssl rand -hex 32)
    echo "[init-mailcue] Auto-generated MAILCUE_SECRET_KEY."
fi
# Persist for use by other s6 services
echo "${SECRET_KEY}" > /var/lib/mailcue/.secret_key
chmod 600 /var/lib/mailcue/.secret_key

# -------------------------------------------------------------------------
# 5. Create the default admin user
# -------------------------------------------------------------------------
echo "[init-mailcue] Creating admin user: ${ADMIN_USER}@${DOMAIN}"

ADMIN_EMAIL="${ADMIN_USER}@${DOMAIN}"
ADMIN_MAILDIR="${VMAIL_BASE}/${DOMAIN}/${ADMIN_USER}"

# -------------------------------------------------------------------------
# Persist Dovecot users + master-users into the /var/lib/mailcue volume so
# API-managed mailbox entries survive `docker compose up -d` recreations.
# Without this, /etc/dovecot/users lives only in the container's writable
# layer and every container recreation strips every mailbox the API ever
# added (only the admin line gets re-templated by this script).
# -------------------------------------------------------------------------
DOVECOT_STATE_DIR="/var/lib/mailcue/dovecot"
mkdir -p "${DOVECOT_STATE_DIR}"
chmod 750 "${DOVECOT_STATE_DIR}"
chown root:dovecot "${DOVECOT_STATE_DIR}" 2>/dev/null || chown root:root "${DOVECOT_STATE_DIR}"

for src in "${DOVECOT_USERS}" /etc/dovecot/master-users; do
    target="${DOVECOT_STATE_DIR}/$(basename "${src}")"
    if [ -L "${src}" ]; then
        # Already a symlink — make sure it points where we expect.
        current=$(readlink "${src}")
        if [ "${current}" != "${target}" ]; then
            rm -f "${src}"
            ln -s "${target}" "${src}"
        fi
    elif [ -f "${src}" ]; then
        # First-time migration: move the existing file into the volume,
        # then replace the original path with a symlink.
        if [ ! -f "${target}" ]; then
            mv "${src}" "${target}"
        else
            # Both exist — prefer the persisted one and discard the
            # in-container copy (which is just the image-baked seed).
            rm -f "${src}"
        fi
        ln -s "${target}" "${src}"
    else
        # No file in either place — create the persisted file empty
        # and symlink. The block below will populate the admin line.
        touch "${target}"
        ln -s "${target}" "${src}"
    fi
    chmod 640 "${target}"
    chown root:dovecot "${target}" 2>/dev/null || chown root:root "${target}"
done

# Generate password hash via doveadm (SHA512-CRYPT)
ADMIN_HASH=$(doveadm pw -s SHA512-CRYPT -p "${ADMIN_PASSWORD}" 2>/dev/null || true)
if [ -z "${ADMIN_HASH}" ]; then
    # Fallback: use PLAIN scheme (acceptable for a testing tool)
    ADMIN_HASH="{PLAIN}${ADMIN_PASSWORD}"
fi

# Initialise Dovecot users file (overwrite on fresh start, preserve on restart)
if [ ! -f "${DOVECOT_USERS}" ] || ! grep -q "^${ADMIN_EMAIL}:" "${DOVECOT_USERS}" 2>/dev/null; then
    touch "${DOVECOT_USERS}"
    echo "${ADMIN_EMAIL}:${ADMIN_HASH}:5000:5000::/var/mail/vhosts/${DOMAIN}/${ADMIN_USER}::" \
        >> "${DOVECOT_USERS}"
fi

# Also add a postmaster alias
if [ ! -f /etc/postfix/virtual_aliases ] || ! grep -q "postmaster@${DOMAIN}" /etc/postfix/virtual_aliases 2>/dev/null; then
    echo "postmaster@${DOMAIN}    ${ADMIN_EMAIL}" >> /etc/postfix/virtual_aliases
fi

# Keep legacy virtual_mailboxes entry for backward compat (not required for catch-all)
if ! grep -q "^${ADMIN_EMAIL}" /etc/postfix/virtual_mailboxes 2>/dev/null; then
    echo "${ADMIN_EMAIL}    ${DOMAIN}/${ADMIN_USER}/" \
        >> /etc/postfix/virtual_mailboxes
fi

# postmap the legacy tables (best-effort; catch-all does not depend on them)
postmap /etc/postfix/virtual_mailboxes 2>/dev/null || true
postmap /etc/postfix/virtual_aliases 2>/dev/null || true

# -------------------------------------------------------------------------
# 5b. Create Dovecot master-users file (for API impersonation)
# -------------------------------------------------------------------------
MASTER_USERS="/etc/dovecot/master-users"
MASTER_USER_NAME="${MAILCUE_IMAP_MASTER_USER:-mailcue-master}"
MASTER_USER_PASS="${MAILCUE_IMAP_MASTER_PASSWORD:-master-secret}"

# Hash the master user password
MASTER_HASH=$(doveadm pw -s SHA512-CRYPT -p "${MASTER_USER_PASS}" 2>/dev/null || true)
if [ -z "${MASTER_HASH}" ]; then
    MASTER_HASH="{PLAIN}${MASTER_USER_PASS}"
fi

if [ ! -f "${MASTER_USERS}" ] || ! grep -q "^${MASTER_USER_NAME}:" "${MASTER_USERS}" 2>/dev/null; then
    touch "${MASTER_USERS}"
    echo "${MASTER_USER_NAME}:${MASTER_HASH}" >> "${MASTER_USERS}"
fi
chmod 640 "${MASTER_USERS}"
chown root:dovecot "${MASTER_USERS}" 2>/dev/null || chown root:root "${MASTER_USERS}"

# -------------------------------------------------------------------------
# 6. Create Maildir structure for admin user
# -------------------------------------------------------------------------
for subdir in cur new tmp; do
    mkdir -p "${ADMIN_MAILDIR}/${subdir}"
done

for folder in .Sent .Drafts .Trash .Junk; do
    for subdir in cur new tmp; do
        mkdir -p "${ADMIN_MAILDIR}/${folder}/${subdir}"
    done
done

# Write Dovecot subscriptions file
cat > "${ADMIN_MAILDIR}/subscriptions" << SUBS
Sent
Drafts
Trash
Junk
SUBS

chown -R vmail:vmail "${VMAIL_BASE}"

# -------------------------------------------------------------------------
# 7. Set correct permissions on all relevant directories
# -------------------------------------------------------------------------
chmod 640 "${DOVECOT_USERS}"
chown root:dovecot "${DOVECOT_USERS}" 2>/dev/null || chown root:root "${DOVECOT_USERS}"

# Postfix chroot needs the Dovecot auth and LMTP sockets directory
mkdir -p /var/spool/postfix/private
chown postfix:postfix /var/spool/postfix/private

# Ensure Postfix data directory exists
mkdir -p /var/lib/postfix
chown postfix:postfix /var/lib/postfix

# Ensure the SQLite database directory exists
mkdir -p "$(dirname "${DB_PATH}")"
chown root:root /var/lib/mailcue

# Nginx directories
mkdir -p /var/www/mailcue
mkdir -p /var/log/nginx
mkdir -p /run

# -------------------------------------------------------------------------
# 7.5 One-time plaintext → encrypted migration (SQLCipher)
#
# Detect what `${DB_PATH}` actually is by reading the first 16 bytes:
#
#   - "SQLite format 3\0"          → plaintext SQLite, convert to encrypted
#   - random ciphertext bytes      → already SQLCipher-encrypted, skip
#   - empty / 0 bytes              → fresh deployment, skip (alembic creates)
#   - non-SQLite garbage           → corrupt DB; fail loudly with guidance
#                                    rather than corrupt it further
# -------------------------------------------------------------------------
if [ -n "${DB_ENCRYPTION_KEY}" ] && [ -f "${DB_PATH}" ]; then
    DB_SIZE=$(stat -c '%s' "${DB_PATH}" 2>/dev/null || echo 0)
    DB_HEADER=$(head -c 16 "${DB_PATH}" 2>/dev/null | tr -d '\0' || true)

    if [ "${DB_SIZE}" = "0" ]; then
        echo "[init-mailcue] DB file is empty — Alembic will create a fresh encrypted DB."
    elif [ "${DB_HEADER#SQLite format 3}" != "${DB_HEADER}" ]; then
        # The plaintext-SQLite magic prefix is present (the trailing NUL
        # was stripped above for a clean compare).
        echo "[init-mailcue] Converting plaintext database to SQLCipher-encrypted format..."
        ENCRYPTED_TMP="${DB_PATH}.encrypted"
        if ! sqlcipher "${DB_PATH}" \
                "ATTACH DATABASE '${ENCRYPTED_TMP}' AS encrypted KEY '${DB_ENCRYPTION_KEY}';" \
                "SELECT sqlcipher_export('encrypted');" \
                "DETACH DATABASE encrypted;"; then
            rm -f "${ENCRYPTED_TMP}"
            echo "[init-mailcue] ERROR: sqlcipher_export failed; refusing to overwrite ${DB_PATH}."
            exit 1
        fi
        mv "${ENCRYPTED_TMP}" "${DB_PATH}"
        echo "[init-mailcue] Database encryption complete."
    else
        # Header doesn't match plaintext SQLite. The DB is either already
        # encrypted (good — leave it for alembic to open with the key) or
        # genuinely corrupt. Quick sanity check: try to open it as an
        # encrypted DB with our key. On success it's encrypted-with-this-key;
        # on failure it's either a different key or random garbage.
        if echo "PRAGMA key='${DB_ENCRYPTION_KEY}'; SELECT count(*) FROM sqlite_master;" \
                | sqlcipher "${DB_PATH}" >/dev/null 2>&1; then
            echo "[init-mailcue] DB is already SQLCipher-encrypted with the provided key — skipping."
        else
            echo "[init-mailcue] ERROR: ${DB_PATH} exists but is neither plaintext SQLite nor"
            echo "[init-mailcue]        decryptable with MAILCUE_DATABASE_ENCRYPTION_KEY."
            echo "[init-mailcue]        - If you rotated the key: restore the previous key, or"
            echo "[init-mailcue]          delete the file (LOSES ALL DATA) and let it recreate."
            echo "[init-mailcue]        - If the file is corrupt: stop the container and remove"
            echo "[init-mailcue]          ${DB_PATH} (LOSES ALL DATA), then start again."
            exit 1
        fi
    fi
fi

# -------------------------------------------------------------------------
# 8. Run Alembic migrations (if the application is installed)
# -------------------------------------------------------------------------
if command -v alembic >/dev/null 2>&1 && [ -f /opt/mailcue/alembic.ini ]; then
    echo "[init-mailcue] Running database migrations..."

    # Export the database URL so alembic/env.py resolves an absolute path.
    # The config.py default uses 3 slashes (relative); we need 4 (absolute).
    export MAILCUE_DATABASE_URL="sqlite+aiosqlite:///${DB_PATH}"

    cd /opt/mailcue

    # Check if alembic_version table exists (i.e. migrations were run before).
    HAS_VERSION=$(python3 -c "
import sqlite3, os
try:
    conn = sqlite3.connect('${DB_PATH}')
    key = os.environ.get('MAILCUE_DATABASE_ENCRYPTION_KEY', '')
    if key:
        conn.execute(\"PRAGMA key='\" + key + \"'\")
    conn.execute('SELECT 1 FROM alembic_version LIMIT 1')
    print('yes')
except Exception:
    print('no')
finally:
    conn.close()
" 2>/dev/null || echo "no")

    if [ "$HAS_VERSION" = "yes" ]; then
        # Managed database — apply pending migrations.
        alembic upgrade head
    else
        # Check if this is a legacy pre-migration DB or a fresh one.
        HAS_USERS=$(python3 -c "
import sqlite3, os
try:
    conn = sqlite3.connect('${DB_PATH}')
    key = os.environ.get('MAILCUE_DATABASE_ENCRYPTION_KEY', '')
    if key:
        conn.execute(\"PRAGMA key='\" + key + \"'\")
    conn.execute('SELECT 1 FROM users LIMIT 1')
    print('yes')
except Exception:
    print('no')
finally:
    conn.close()
" 2>/dev/null || echo "no")

        if [ "$HAS_USERS" = "yes" ]; then
            # Legacy database — stamp at initial migration, then upgrade.
            echo "[init-mailcue] Legacy database detected, stamping and upgrading..."
            alembic stamp 001_initial
            alembic upgrade head
        else
            # Fresh database — run all migrations from scratch.
            alembic upgrade head
        fi
    fi

    echo "[init-mailcue] Database migrations complete."
fi

# -------------------------------------------------------------------------
# 9. GPG keyring directory
# -------------------------------------------------------------------------
echo "[init-mailcue] Step 9: Setting up GPG keyring directory..."
mkdir -p /var/lib/mailcue/gpg
chmod 700 /var/lib/mailcue/gpg
echo "[init-mailcue] GPG keyring directory ready"

echo "[init-mailcue] Initialisation complete."
