#!/bin/sh
# =============================================================================
# MailCue — Container Initialisation (oneshot)
# Runs once before any long-running services start.
# =============================================================================
set -eu

DOMAIN="${MAILCUE_DOMAIN:-mailcue.local}"
HOSTNAME="${MAILCUE_HOSTNAME:-mail.${DOMAIN}}"
ADMIN_USER="${MAILCUE_ADMIN_USER:-admin}"
ADMIN_PASSWORD="${MAILCUE_ADMIN_PASSWORD:-mailcue}"
SECRET_KEY="${MAILCUE_SECRET_KEY:-}"
DB_PATH="${MAILCUE_DB_PATH:-/var/lib/mailcue/mailcue.db}"
DB_ENCRYPTION_KEY="${MAILCUE_DATABASE_ENCRYPTION_KEY:-}"
SSL_DIR="/etc/ssl/mailcue"
DKIM_DIR="/etc/opendkim/keys/${DOMAIN}"
VMAIL_BASE="/var/mail/vhosts"
DOVECOT_USERS="/etc/dovecot/users"

echo "[init-mailcue] Starting initialisation for domain=${DOMAIN}"

# -------------------------------------------------------------------------
# 1. Generate self-signed TLS certificates (if not already present)
# -------------------------------------------------------------------------
if [ ! -f "${SSL_DIR}/server.crt" ] || [ ! -f "${SSL_DIR}/server.key" ]; then
    echo "[init-mailcue] Generating TLS certificates (CA + server)..."
    mkdir -p "${SSL_DIR}"

    SERIAL_HEX=$(openssl rand -hex 8)

    # --- Root CA ---
    cat > /tmp/mailcue-ca.cnf << 'CACNF'
[req]
default_bits       = 4096
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_ca

[dn]
C            = US
ST           = Georgia
L            = Stone Mountain
O            = Olib AI
OU           = MailCue Certificate Authority
CN           = MailCue Root CA
emailAddress = security@olib.ai

[v3_ca]
basicConstraints     = critical, CA:TRUE, pathlen:0
keyUsage             = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always, issuer
nsComment            = "MailCue Root CA - Generated by MailCue (olib.ai)"
CACNF

    openssl req -x509 -newkey rsa:4096 -nodes \
        -keyout "${SSL_DIR}/ca.key" \
        -out "${SSL_DIR}/ca.crt" \
        -days 3650 \
        -config /tmp/mailcue-ca.cnf 2>/dev/null

    # --- Server certificate CSR config ---
    cat > /tmp/mailcue-server-req.cnf << REQCNF
[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn

[dn]
C            = US
ST           = Georgia
L            = Stone Mountain
O            = Olib AI
OU           = MailCue Mail Server
CN           = ${HOSTNAME}
emailAddress = security@olib.ai
REQCNF

    # --- Server certificate extensions (applied at signing time) ---
    cat > /tmp/mailcue-server-ext.cnf << EXTCNF
basicConstraints       = critical, CA:FALSE
keyUsage               = critical, digitalSignature, keyEncipherment, keyAgreement
extendedKeyUsage       = serverAuth, clientAuth, emailProtection
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid, issuer
subjectAltName         = @alt_names
nsComment              = "MailCue Server Certificate - Generated by MailCue (olib.ai)"
certificatePolicies    = 2.23.140.1.2.1

[alt_names]
DNS.1  = ${HOSTNAME}
DNS.2  = smtp.${DOMAIN}
DNS.3  = imap.${DOMAIN}
DNS.4  = pop3.${DOMAIN}
DNS.5  = webmail.${DOMAIN}
DNS.6  = ${DOMAIN}
DNS.7  = *.${DOMAIN}
DNS.8  = localhost
IP.1   = 127.0.0.1
IP.2   = ::1
email.1 = security@olib.ai
EXTCNF

    # Generate server key and CSR
    openssl req -newkey rsa:2048 -nodes \
        -keyout "${SSL_DIR}/server.key" \
        -out /tmp/mailcue-server.csr \
        -config /tmp/mailcue-server-req.cnf 2>/dev/null

    # Sign server cert with CA, applying extensions
    openssl x509 -req \
        -in /tmp/mailcue-server.csr \
        -CA "${SSL_DIR}/ca.crt" \
        -CAkey "${SSL_DIR}/ca.key" \
        -set_serial "0x${SERIAL_HEX}" \
        -days 3650 \
        -sha256 \
        -extfile /tmp/mailcue-server-ext.cnf \
        -out "${SSL_DIR}/server-only.crt" 2>/dev/null

    # Build full chain: server cert + CA cert
    cat "${SSL_DIR}/server-only.crt" "${SSL_DIR}/ca.crt" > "${SSL_DIR}/server.crt"

    chmod 600 "${SSL_DIR}/server.key" "${SSL_DIR}/ca.key"
    chmod 644 "${SSL_DIR}/server.crt" "${SSL_DIR}/ca.crt" "${SSL_DIR}/server-only.crt"
    rm -f /tmp/mailcue-ca.cnf /tmp/mailcue-server-req.cnf /tmp/mailcue-server-ext.cnf /tmp/mailcue-server.csr
    echo "[init-mailcue] TLS certificates generated (CA + server chain)."
else
    echo "[init-mailcue] TLS certificate already exists, skipping generation."
fi

# -------------------------------------------------------------------------
# 2. Generate DKIM keys (if not already present)
# -------------------------------------------------------------------------
if [ ! -f "${DKIM_DIR}/mail.private" ]; then
    echo "[init-mailcue] Generating DKIM keys for ${DOMAIN}..."
    mkdir -p "${DKIM_DIR}"

    opendkim-genkey -b 2048 -h rsa-sha256 \
        -d "${DOMAIN}" -s mail \
        -D "${DKIM_DIR}/"

    chown -R opendkim:opendkim /etc/opendkim/keys/
    chmod 600 "${DKIM_DIR}/mail.private"
    echo "[init-mailcue] DKIM keys generated."
else
    echo "[init-mailcue] DKIM keys already exist, skipping generation."
fi

# -------------------------------------------------------------------------
# 3. Template mail server configuration files with runtime values
# -------------------------------------------------------------------------
echo "[init-mailcue] Templating configuration files..."

# --- Postfix main.cf ---
sed -i \
    -e "s/\${MAILCUE_DOMAIN}/${DOMAIN}/g" \
    -e "s/\${MAILCUE_HOSTNAME}/${HOSTNAME}/g" \
    /etc/postfix/main.cf

# --- Dovecot postmaster address ---
sed -i \
    -e "s/postmaster@mailcue\.local/postmaster@${DOMAIN}/g" \
    /etc/dovecot/dovecot.conf

# --- Postfix catch-all domain table ---
# Regexp table: match any domain.  Does NOT need postmap.
printf '/^.+$/    OK\n' > /etc/postfix/virtual_domains_catchall

# Keep legacy hash files for backward compat but they are no longer
# referenced by the main delivery path (catch-all replaces them).
touch /etc/postfix/virtual_mailboxes
touch /etc/postfix/virtual_aliases
touch /etc/postfix/virtual_domains

# --- OpenDKIM tables ---
echo "mail._domainkey.${DOMAIN}    ${DOMAIN}:mail:${DKIM_DIR}/mail.private" \
    > /etc/opendkim/KeyTable
echo "*@${DOMAIN}    mail._domainkey.${DOMAIN}" \
    > /etc/opendkim/SigningTable
cat > /etc/opendkim/TrustedHosts << TRUSTED
127.0.0.1
::1
localhost
${HOSTNAME}
*.${DOMAIN}
TRUSTED

chown -R opendkim:opendkim /etc/opendkim/

# -------------------------------------------------------------------------
# 3b. Configure OpenDMARC
# -------------------------------------------------------------------------
echo "[init-mailcue] Configuring OpenDMARC..."
mkdir -p /var/run/opendmarc
chown opendmarc:opendmarc /var/run/opendmarc 2>/dev/null || true

# Template the config with the domain
sed -i \
    -e "s/postmaster@localhost/postmaster@${DOMAIN}/g" \
    /etc/opendmarc/opendmarc.conf 2>/dev/null || true

# -------------------------------------------------------------------------
# 3c. Configure smarthost relay (if MAILCUE_RELAY_HOST is set)
# -------------------------------------------------------------------------
RELAY_HOST="${MAILCUE_RELAY_HOST:-}"
RELAY_PORT="${MAILCUE_RELAY_PORT:-587}"
RELAY_USER="${MAILCUE_RELAY_USER:-}"
RELAY_PASSWORD="${MAILCUE_RELAY_PASSWORD:-}"

if [ -n "${RELAY_HOST}" ]; then
    echo "[init-mailcue] Configuring smarthost relay: ${RELAY_HOST}:${RELAY_PORT}"

    # Update Postfix main.cf
    cat >> /etc/postfix/main.cf << RELAY
# --- Smarthost relay (auto-configured) ---
relayhost = [${RELAY_HOST}]:${RELAY_PORT}
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_tls_security_level = encrypt
RELAY

    # Create SASL password file
    echo "[${RELAY_HOST}]:${RELAY_PORT} ${RELAY_USER}:${RELAY_PASSWORD}" > /etc/postfix/sasl_passwd
    postmap /etc/postfix/sasl_passwd
    chmod 600 /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db
    echo "[init-mailcue] Smarthost relay configured."
fi

# -------------------------------------------------------------------------
# 4. Generate a secret key if none provided
# -------------------------------------------------------------------------
if [ -z "${SECRET_KEY}" ] && [ -f /var/lib/mailcue/.secret_key ]; then
    # Reuse the previously persisted key so encrypted TOTP secrets remain valid.
    SECRET_KEY=$(cat /var/lib/mailcue/.secret_key)
    echo "[init-mailcue] Loaded MAILCUE_SECRET_KEY from persisted file."
elif [ -z "${SECRET_KEY}" ]; then
    SECRET_KEY=$(openssl rand -hex 32)
    echo "[init-mailcue] Auto-generated MAILCUE_SECRET_KEY."
fi
# Persist for use by other s6 services
echo "${SECRET_KEY}" > /var/lib/mailcue/.secret_key
chmod 600 /var/lib/mailcue/.secret_key

# -------------------------------------------------------------------------
# 5. Create the default admin user
# -------------------------------------------------------------------------
echo "[init-mailcue] Creating admin user: ${ADMIN_USER}@${DOMAIN}"

ADMIN_EMAIL="${ADMIN_USER}@${DOMAIN}"
ADMIN_MAILDIR="${VMAIL_BASE}/${DOMAIN}/${ADMIN_USER}"

# Generate password hash via doveadm (SHA512-CRYPT)
ADMIN_HASH=$(doveadm pw -s SHA512-CRYPT -p "${ADMIN_PASSWORD}" 2>/dev/null || true)
if [ -z "${ADMIN_HASH}" ]; then
    # Fallback: use PLAIN scheme (acceptable for a testing tool)
    ADMIN_HASH="{PLAIN}${ADMIN_PASSWORD}"
fi

# Initialise Dovecot users file (overwrite on fresh start, preserve on restart)
if [ ! -f "${DOVECOT_USERS}" ] || ! grep -q "^${ADMIN_EMAIL}:" "${DOVECOT_USERS}" 2>/dev/null; then
    touch "${DOVECOT_USERS}"
    echo "${ADMIN_EMAIL}:${ADMIN_HASH}:5000:5000::/var/mail/vhosts/${DOMAIN}/${ADMIN_USER}::" \
        >> "${DOVECOT_USERS}"
fi

# Also add a postmaster alias
if [ ! -f /etc/postfix/virtual_aliases ] || ! grep -q "postmaster@${DOMAIN}" /etc/postfix/virtual_aliases 2>/dev/null; then
    echo "postmaster@${DOMAIN}    ${ADMIN_EMAIL}" >> /etc/postfix/virtual_aliases
fi

# Keep legacy virtual_mailboxes entry for backward compat (not required for catch-all)
if ! grep -q "^${ADMIN_EMAIL}" /etc/postfix/virtual_mailboxes 2>/dev/null; then
    echo "${ADMIN_EMAIL}    ${DOMAIN}/${ADMIN_USER}/" \
        >> /etc/postfix/virtual_mailboxes
fi

# postmap the legacy tables (best-effort; catch-all does not depend on them)
postmap /etc/postfix/virtual_mailboxes 2>/dev/null || true
postmap /etc/postfix/virtual_aliases 2>/dev/null || true

# -------------------------------------------------------------------------
# 5b. Create Dovecot master-users file (for API impersonation)
# -------------------------------------------------------------------------
MASTER_USERS="/etc/dovecot/master-users"
MASTER_USER_NAME="${MAILCUE_IMAP_MASTER_USER:-mailcue-master}"
MASTER_USER_PASS="${MAILCUE_IMAP_MASTER_PASSWORD:-master-secret}"

# Hash the master user password
MASTER_HASH=$(doveadm pw -s SHA512-CRYPT -p "${MASTER_USER_PASS}" 2>/dev/null || true)
if [ -z "${MASTER_HASH}" ]; then
    MASTER_HASH="{PLAIN}${MASTER_USER_PASS}"
fi

if [ ! -f "${MASTER_USERS}" ] || ! grep -q "^${MASTER_USER_NAME}:" "${MASTER_USERS}" 2>/dev/null; then
    touch "${MASTER_USERS}"
    echo "${MASTER_USER_NAME}:${MASTER_HASH}" >> "${MASTER_USERS}"
fi
chmod 640 "${MASTER_USERS}"
chown root:dovecot "${MASTER_USERS}" 2>/dev/null || chown root:root "${MASTER_USERS}"

# -------------------------------------------------------------------------
# 6. Create Maildir structure for admin user
# -------------------------------------------------------------------------
for subdir in cur new tmp; do
    mkdir -p "${ADMIN_MAILDIR}/${subdir}"
done

for folder in .Sent .Drafts .Trash .Junk; do
    for subdir in cur new tmp; do
        mkdir -p "${ADMIN_MAILDIR}/${folder}/${subdir}"
    done
done

# Write Dovecot subscriptions file
cat > "${ADMIN_MAILDIR}/subscriptions" << SUBS
Sent
Drafts
Trash
Junk
SUBS

chown -R vmail:vmail "${VMAIL_BASE}"

# -------------------------------------------------------------------------
# 7. Set correct permissions on all relevant directories
# -------------------------------------------------------------------------
chmod 640 "${DOVECOT_USERS}"
chown root:dovecot "${DOVECOT_USERS}" 2>/dev/null || chown root:root "${DOVECOT_USERS}"

# Postfix chroot needs the Dovecot auth and LMTP sockets directory
mkdir -p /var/spool/postfix/private
chown postfix:postfix /var/spool/postfix/private

# Ensure Postfix data directory exists
mkdir -p /var/lib/postfix
chown postfix:postfix /var/lib/postfix

# Ensure the SQLite database directory exists
mkdir -p "$(dirname "${DB_PATH}")"
chown root:root /var/lib/mailcue

# Nginx directories
mkdir -p /var/www/mailcue
mkdir -p /var/log/nginx
mkdir -p /run

# -------------------------------------------------------------------------
# 7.5 One-time plaintext → encrypted migration (SQLCipher)
# -------------------------------------------------------------------------
if [ -n "${DB_ENCRYPTION_KEY}" ] && [ -f "${DB_PATH}" ]; then
    # Probe whether the existing DB is still plaintext
    IS_PLAINTEXT=$(python3 -c "
import sqlite3
try:
    conn = sqlite3.connect('${DB_PATH}')
    conn.execute('SELECT 1')
    print('yes')
except Exception:
    print('no')
finally:
    conn.close()
" 2>/dev/null || echo "no")

    if [ "$IS_PLAINTEXT" = "yes" ]; then
        echo "[init-mailcue] Converting plaintext database to SQLCipher-encrypted format..."
        ENCRYPTED_TMP="${DB_PATH}.encrypted"
        sqlcipher "${DB_PATH}" \
            "ATTACH DATABASE '${ENCRYPTED_TMP}' AS encrypted KEY '${DB_ENCRYPTION_KEY}';" \
            "SELECT sqlcipher_export('encrypted');" \
            "DETACH DATABASE encrypted;"
        mv "${ENCRYPTED_TMP}" "${DB_PATH}"
        echo "[init-mailcue] Database encryption complete."
    fi
fi

# -------------------------------------------------------------------------
# 8. Run Alembic migrations (if the application is installed)
# -------------------------------------------------------------------------
if command -v alembic >/dev/null 2>&1 && [ -f /opt/mailcue/alembic.ini ]; then
    echo "[init-mailcue] Running database migrations..."

    # Export the database URL so alembic/env.py resolves an absolute path.
    # The config.py default uses 3 slashes (relative); we need 4 (absolute).
    export MAILCUE_DATABASE_URL="sqlite+aiosqlite:///${DB_PATH}"

    cd /opt/mailcue

    # Check if alembic_version table exists (i.e. migrations were run before).
    HAS_VERSION=$(python3 -c "
import sqlite3, os
try:
    conn = sqlite3.connect('${DB_PATH}')
    key = os.environ.get('MAILCUE_DATABASE_ENCRYPTION_KEY', '')
    if key:
        conn.execute(\"PRAGMA key='\" + key + \"'\")
    conn.execute('SELECT 1 FROM alembic_version LIMIT 1')
    print('yes')
except Exception:
    print('no')
finally:
    conn.close()
" 2>/dev/null || echo "no")

    if [ "$HAS_VERSION" = "yes" ]; then
        # Managed database — apply pending migrations.
        alembic upgrade head
    else
        # Check if this is a legacy pre-migration DB or a fresh one.
        HAS_USERS=$(python3 -c "
import sqlite3, os
try:
    conn = sqlite3.connect('${DB_PATH}')
    key = os.environ.get('MAILCUE_DATABASE_ENCRYPTION_KEY', '')
    if key:
        conn.execute(\"PRAGMA key='\" + key + \"'\")
    conn.execute('SELECT 1 FROM users LIMIT 1')
    print('yes')
except Exception:
    print('no')
finally:
    conn.close()
" 2>/dev/null || echo "no")

        if [ "$HAS_USERS" = "yes" ]; then
            # Legacy database — stamp at initial migration, then upgrade.
            echo "[init-mailcue] Legacy database detected, stamping and upgrading..."
            alembic stamp 001_initial
            alembic upgrade head
        else
            # Fresh database — run all migrations from scratch.
            alembic upgrade head
        fi
    fi

    echo "[init-mailcue] Database migrations complete."
fi

# -------------------------------------------------------------------------
# 9. GPG keyring directory
# -------------------------------------------------------------------------
echo "[init-mailcue] Step 9: Setting up GPG keyring directory..."
mkdir -p /var/lib/mailcue/gpg
chmod 700 /var/lib/mailcue/gpg
echo "[init-mailcue] GPG keyring directory ready"

echo "[init-mailcue] Initialisation complete."
